"""Assembler — builds the final `brand_kit/` + `brand_guide.md` + `kit_manifest.json`.

Called by the runner (CP-008) after the generate→critique loop. Copies approved
renders to canonical kit names, writes a human-readable brand guide (palette swatches,
typography, do/don't, asset list), and emits the validated `kit_manifest.json` with
optimization stats drawn from the Model Orchestrator's evidence trail.
"""

from __future__ import annotations

import shutil
from datetime import UTC, datetime
from pathlib import Path
from typing import Literal

import structlog

from src.common.runs import RunDir
from src.common.schemas import (
    AssetManifest,
    BrandDna,
    KitAsset,
    KitManifest,
    OptimizationStats,
)

__all__ = ["assemble_kit", "render_brand_guide"]

_log = structlog.get_logger(__name__)


def render_brand_guide(dna: BrandDna, kit_assets: list[KitAsset]) -> str:
    palette_rows = "\n".join(f"| {c.name} | `{c.hex}` | {c.rank} |" for c in dna.palette)
    mood = ", ".join(dna.mood)
    keywords = ", ".join(dna.visual_keywords)
    pairs = "; ".join(f"{k}: {v}" for k, v in dna.typography_pairs.items()) or "—"
    dos = "\n".join(f"- {d}" for d in dna.dos) or "—"
    donts = "\n".join(f"- {d}" for d in dna.donts) or "—"
    asset_lines = "\n".join(
        f"- **{a.id}** (`{a.type}`) — {a.status}"
        + (f", score {a.final_score}" if a.final_score is not None else "")
        + (f" — _{a.error}_" if a.error else "")
        for a in kit_assets
    )
    return (
        f"# {dna.brand_name} — Brand Guide\n\n"
        f"_Generated by StyleForge._\n\n"
        "## Palette\n\n"
        "| name | hex | rank |\n|---|---|---|\n"
        f"{palette_rows}\n\n"
        "## Typography\n\n"
        f"- class: `{dna.typography_class}`\n"
        f"- pairs: {pairs}\n\n"
        "## Mood\n\n"
        f"{mood}\n\n"
        "## Visual keywords\n\n"
        f"{keywords}\n\n"
        "## Do\n\n"
        f"{dos}\n\n"
        "## Don't\n\n"
        f"{donts}\n\n"
        "## Assets\n\n"
        f"{asset_lines}\n\n"
        f"## Personality\n\n"
        f"{dna.personality}\n"
    )


async def assemble_kit(
    run_dir: RunDir,
    manifest: AssetManifest,
    brand_dna: BrandDna,
    kit_assets: list[KitAsset],
    *,
    total_latency_s: float,
    stats: OptimizationStats,
) -> KitManifest:
    """Copy approved renders to canonical names and write the kit manifest + guide."""
    run_dir.path.mkdir(parents=True, exist_ok=True)
    for ka in kit_assets:
        if ka.status == "approved" and ka.path:
            src = Path(ka.path)
            if src.exists():
                dst = run_dir.kit_asset_path(f"{ka.id}.png")
                shutil.copyfile(src, dst)
                ka.path = f"brand_kit/{ka.id}.png"

    guide_path = run_dir.kit_asset_path("brand_guide.md")
    guide_path.write_text(render_brand_guide(brand_dna, kit_assets), encoding="utf-8")

    status: Literal["complete", "partial"] = (
        "complete" if kit_assets and all(a.status == "approved" for a in kit_assets) else "partial"
    )
    kit = KitManifest(
        run_id=run_dir.run_id,
        brand_name=brand_dna.brand_name,
        status=status,
        assets=kit_assets,
        palette=[c.hex for c in brand_dna.palette],
        generated_at=datetime.now(UTC),
        total_latency_s=int(total_latency_s),
        optimization_stats=stats,
    )
    run_dir.kit_manifest_path().write_text(kit.model_dump_json(indent=2), encoding="utf-8")
    _log.info(
        "assembler.done",
        run_id=run_dir.run_id,
        status=status,
        approved=sum(1 for a in kit_assets if a.status == "approved"),
        failed=sum(1 for a in kit_assets if a.status == "failed"),
    )
    return kit
